# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Junk Miles
tagline:             Musings on tech, running, and other bits..
description:         Mostly tech, sometimes running, hiking, or other outdoorsy topics may crop up.
url:                 http://jsimpson.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jonathan Simpson
  url:               https://twitter.com/thatdamnsimpson
  email:             jsimpson.github@gmail.com

# Custom vars
version:             1.0.2

# syntax highlighting
highlighter: rouge
